# enable color support of ls and also add handy aliases
if [ "$TERM" != "dumb" ]; then
  eval "`dircolors -b`"
  alias ls='ls --color=auto'
fi

alias rake='~/Environment/Bin/rake-notify'
alias mvn3='/opt/maven3/bin/mvn 2>&1 clean install | tee buildlog.latest.txt'
alias cmake='cmake -DCMAKE_PREFIX=/usr -DCMAKE_INSTALL_PREFIX=/usr'

alias gp='git push --all origin'
alias gl='git pull --rebase origin'
alias ga='git add'
alias gc='git commit'
alias gs='git status'

alias sp='bundle exec rspec spec/**_spec.rb'

export PATH="$HOME/Environment/Modules/rbenv/bin:$PATH"

eval "$(rbenv init -)"

