# enable color support of ls and also add handy aliases
if [ "$TERM" != "dumb" ]; then
  eval "`dircolors -b`"
  alias ls='ls --color=auto'
fi

alias rake='~/Environment/bin/rake-notify'

alias gp='git push --all origin'
alias gl='git pull --rebase origin'
alias ga='git add'
alias gc='git commit'
alias gs='git status'

alias sp='bundle exec rspec spec/**_spec.rb'

alias be='bundle exec'

export PATH="$HOME/Environment/local/rbenv/bin:$PATH"

eval "$(rbenv init -)"

